#!/usr/bin/env node
// Generate a local TypeScript module; esbuild bundles its decoder for offline use.
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { encode, decode } from 'base32768';

export function packBytes(bytes) {
  const encoded = encode(bytes);
  const restored = decode(encoded);
  if (restored.length !== bytes.length || restored.some((byte, i) => byte !== bytes[i])) {
    throw new Error('Base32768 round-trip verification failed');
  }
  return {
    source: '// Generated by the component skill pack-data.mjs helper.\n' +
      "import { decode } from 'base32768';\n" +
      'export function unpack(): Uint8Array {\n' +
      `  return decode(${JSON.stringify(encoded)});\n}\n`,
    inputBytes: bytes.length,
    base64Chars: 4 * Math.ceil(bytes.length / 3),
    packedChars: encoded.length,
  };
}

async function main(args) {
  if (args.length !== 2 || !args[1].endsWith('.ts')) {
    throw new Error('Usage: node pack-data.mjs <input-file> <new-output.ts>');
  }
  const [input, output] = args;
  const packed = packBytes(await readFile(input));
  // Never overwrite source assets or an existing hand-authored module.
  await writeFile(output, packed.source, { encoding: 'utf8', flag: 'wx' });
  console.log(`${packed.inputBytes} bytes → ${packed.packedChars} Base32768 chars ` +
    `(Base64: ${packed.base64Chars}). Wrote ${output}.\n` +
    'Payload counts exclude decoder/call-site overhead; compare the final npm run build count.');
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2)).catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
