// Generated by the component skill pack-data.mjs helper.
import { decode } from 'base32768';
export function unpack(): Uint8Array {
  return decode("揱䍚哭沲㠑⦺羥輟浰抇饰ዢ蝳堅輪飁山㓈淥鶖䇓䰁軜䙯㭐䅚哬綆⥡ވ蒠喏㙒㩘咬㴒䝑囩缲铅忱㓈猭㵧䇢頙贪觏嶒☫ᗍ趶蝱軩彊嚐㹘☫ᗌ嵖酳䯹礼趂䍑㾳㙤丰ɷ");
}
